export { default as girl } from './Home/girl.webp'
export { default as weed } from './Home/weed.webp'

export { default as pic01 } from './Home/01.jpg'
export { default as pic02 } from './Home/02.jpg'
export { default as pic03 } from './Home/03.jpg'
export { default as pic04 } from './Home/04.jpg'
export { default as pic05 } from './Home/05.jpg'
export { default as pic06 } from './Home/06.jpg'
export { default as pic07 } from './Home/07.jpg'
export { default as pic08 } from './Home/08.jpg'
export { default as pic09 } from './Home/09.jpg'
export { default as pic10 } from './Home/10.jpg'
export { default as pic11 } from './Home/11.jpg'
export { default as pic12 } from './Home/12.jpg'
